### ISSUE TITLE
git clone of kernel errors out

### ISSUE THREAD

**Issue by kirtr** [andrum99/zfs-for-pi#1]
This command errors out:
git clone https://github.com/raspberrypi/linux/archive/raspberrypi-kernel_1.20190925-1.tar.gz
Cloning into 'raspberrypi-kernel_1.20190925-1.tar.gz'...
remote: Not Found
fatal: repository 'https://github.com/raspberrypi/linux/archive/raspberrypi-kernel_1.20190925-1.tar.gz/' not found

This seems to work instead:
wget https://github.com/raspberrypi/linux/archive/raspberrypi-kernel_1.20190925-1.tar.gz
tar xvf raspberrypi-kernel_1.20190925-1.tar.gz

**Comment by andrum99** [comment]
Thanks for the bug report - I've merged a fix for this directly into master.
