### ISSUE TITLE
ZFS build failure in build64.h

### ISSUE THREAD

**Issue by procount** [andrum99/zfs-for-pi#6]
I just updated from your repo and tried rebuilding zfs, but it failed with the following error when configuring to build zfs in build64.sh
```
checking kernel source directory... ~/linux-raspberrypi-kernel_1.20200212-1
configure: error: 
	*** Please make sure the kernel devel package for your distribution
	*** is installed and then try again.  If that fails, you can specify the
	*** location of the kernel source with the '--with-linux=PATH' option.
```

**Comment by andrum99** [comment]
Someone proposed a PR (see #5) that changed the scripts to cope with the case where the user running them wasn't 'pi'. I added to it, and integrated it recently. Unfortunately it seems the configure script for building ZFS doesn't like the that was added in place of /home/pi.

As a workaround you can edit line 59 of build64.sh to replace ~ with e.g. /home/pi. I'm looking at a fix, which may involve using the $HOME variable.

**Comment by procount** [comment]
Yes, I just discovered that, changed it to /home/pi and it's continuing.

**Comment by andrum99** [comment]
Fixed by https://github.com/andrum99/zfs-for-pi/commit/b9e11ad7c74b5ad362f3fc3e87ce5d0e22109882
